### ISSUE TITLE
Improving Documentation (Readme)

### ISSUE THREAD

**Issue by Turnerj** [Turnerj/forem-dotnet#17]
Currently the readme is pretty light on documentation and doesn't even link to the appropriate DEV API documentation for the endpoints that are exposed. It would be useful adding links and examples where appropriate.

**Comment by Turnerj** [comment]
Yep - I saw that other issue which mentions the same thing, good pick up on the issue. Like I explained there, basically `HttpClient` is a dependency that the user would ideally configure. The `GetService` should actually be `GetRequiredService` for better exception handling rather than a `NullPointerException`.

You need a snippet like this in the DI root, it adds a `HttpClient`.

```csharp
services.AddHttpClient();
services.AddTransient(provider =>
{
	//This is a workaround till .NET 5 which fixes the issue of no default HttpClient
	return provider.GetRequiredService<IHttpClientFactory>().CreateClient(string.Empty);
});
```

**Comment by Hilyas68** [comment]
Cool. Thanks
