### ISSUE TITLE
Rename and refactor to Forem

### ISSUE THREAD

**Issue by Turnerj** [Turnerj/forem-dotnet#19]
As DEV broadens and has the codebase re-launched as Forem, it would be appropriate to rename and refactor the library to match.

See Ben's post: https://dev.to/devteam/for-empowering-community-2k6h

The repository itself will be renamed at a later date once this is done.

**Comment by insight001** [comment]
Hi @Turnerj ,

I will like to help with this.

_This is my first time contributing to open source projects_

**Comment by Turnerj** [comment]
Hey @insight001 - that's fantastic that you want to help and that this is your first time contributing to open source! Happy to have you work on this change.

For the actual changes, I'm thinking the following:
- Change namespace references of "DevTo" to "Forem"
- Update ReadMe to reference "Forem" (though note how it was formerly "DevTo", possibly linking off to the link I have in the issue description about Forem)
- Change `AddDevToApi` method name to `AddForemApi`

Don't worry about updating the project names or solution name for now as the build scripts currently reference them. Same goes with updates to the "Directory.Build.props" files - they can still reference "DevTo" for now.

Let me know if you have any questions or need any help with anything. 🙂

**Comment by insight001** [comment]
Alright, Thanks for the detailed response

Will get on it immediately.

**Comment by Turnerj** [comment]
Thanks again for doing the changes here @insight001 - the only ones left are ones I need to do to the repository etc (change repo name, changing package name). At the moment I will leave them as-is as there are some side effects from those changes that I need to make sure I account for. 🙂

**Comment by Turnerj** [comment]
Repository and description is updated - hopefully no issues arise from CI or other integrations. For the CS Project and Nuget package, I'm thinking I will have to do two consecutive releases - one where I put an `Obsolete` attribute on the main classes and publish that under "DevTo.Api" library with updated descriptions about "Don't use this going forward, use 'Forem.Api'".

**Comment by insight001** [comment]
That's great

**Comment by fgiuliani** [comment]
@Turnerj what's left here?

**Comment by Turnerj** [comment]
Just finished this up right now - the "DevTo.Api" package on NuGet is deprecated and a new "Forem.Api" package is published. 😀

**Comment by fgiuliani** [comment]
🚀
