### ISSUE TITLE
Reconsider target frameworks

### ISSUE THREAD

**Issue by Turnerj** [Turnerj/forem-dotnet#25]
Currently we target .NET Standard 2.0 and while that isn't a particular issue, as .NET Standard isn't really a thing in the future, it might be worth targeting specific versions.

Our tests currently target:
- .NET Core 2.2
- .NET Core 3.0

[Neither of those versions are supported anymore.](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

The LTS versions of .NET Core (2.1 and 3.1) have support for at least another year so would make better targets.

To support these changes is relatively simple however the build scripts likely need to be updated to reference these specific versions in case the CI doesn't have them installed.

**Comment by SholomAber** [comment]
@Turnerj , at this point would you want to target .Net 6?

**Comment by Turnerj** [comment]
Yeah - it'd be likely targeting .NET Core 3.1 and .NET 6

**Comment by SholomAber** [comment]
Nice, https://github.com/Turnerj/forem-dotnet/pull/73 should address this. Tests are passing!
