### ISSUE TITLE
Add Users API

### ISSUE THREAD

**Issue by Turnerj** [Turnerj/forem-dotnet#26]
API: https://docs.dev.to/api/#tag/users

> For implementing it, you can use my `ArticleService` class as a guide and create an appropriate interface like how I have `IArticleApi`. The `ApiService` class provides the helper methods for constructing the requests for GET and PUT.

**Comment by fgiuliani** [comment]
Can I work on this one?

**Comment by Turnerj** [comment]
Yep!

**Comment by fgiuliani** [comment]
Created a PR with Users API
https://github.com/Turnerj/devto-dotnet/pull/31

There are some endpoints that appear under "users" category in the API doc but they are really endpoints related to articles. I will take a look to the existing articles endpoints and improve them / add the missing ones in a separate PR

**Comment by Turnerj** [comment]
Regarding what you mentioned about endpoints that appear under "users" but really relate to Articles, feel free to open a PR about that and refer to this issue again. 🙂
