### ISSUE TITLE
Outdated article creation request body 

### ISSUE THREAD

**Issue by ayodejii** [Turnerj/forem-dotnet#88]
Is this repo getting updated soon? I'm looking to make PRs, but I need to point this out first

The current request body for creating new article on this version is [this:](https://developers.forem.com/api/v0#tag/articles/operation/createArticle)

```JSON
{
  "article": {
    "title": "Hello, World!",
    "published": true,
    "body_markdown": "Hello DEV, this is my first post",
    "tags": [
      "discuss",
      "help"
    ],
    "series": "Hello series"
  }
}
```
and what this repo has is [this:](https://github.com/Turnerj/forem-dotnet/blob/master/src/Forem.Api/Models/UserArticle.cs)

```csharp

public class UserArticle : Article
{
    [JsonProperty("page_views_count")]
    public int NumberOfPageViews { get; set; }
    [JsonProperty("published")]
    public bool Published { get; set; }
    [JsonProperty("body_markdown")]
    public bool BodyMarkdown { get; set; }

    [JsonProperty("flare_tag")]
    public FlareTag FlareTag { get; set; }
}
```
I'm guessing this is an update issue, but I thought I need to point it out to see if there is something I'm missing before I make commits.

**Comment by Turnerj** [comment]
Hey @ayodejii !

> Is this repo getting updated soon? I'm looking to make PRs, but I need to point this out first

I'm not _not_ updating the project but I haven't put in really any more time into the project recently. If you found a problem or an API that is incorrect, I'd happily take a PR for it as long as it fits the general patterns of the existing code etc.

One of the things you're going to find with the API is that it is inconsistent all over the place. For example, you're right, the create API takes an array of tags under the `tags` property and returns a `tags` and `tags_list` property when you do. When you call [the API to get users](https://developers.forem.com/api/v0#tag/articles/operation/getUserArticles), there isn't a `tags` property but a `tags_list` property but unlike the `tags_list` property that is returned when you create an article, this one is an array.

I actually have [a fairly detailed issue](https://github.com/forem/forem/issues/4637) I raised about it on the Forem repository and while I would have liked there to be progress there, it looks like the V1 of the API is currently stalled.

Now, I could build individual and incompatible models for each API endpoint but that would have increased the maintenance burden significantly. I could alternatively build some system to better map the incoming data to a more fixed model but that is complicated in its own ways.

It does look like I'm missing the `series` property on [`Article`](https://github.com/Turnerj/forem-dotnet/blob/master/src/Forem.Api/Models/Article.cs) which might be worth while adding.

But yeah, if you find missing fields or other bugs, I'm happy to consider PRs to add them. I want to avoid inconsistency so if you happen to find one of those, that might be a case where I avoid it.

**Comment by ayodejii** [comment]
Thank you for your reply.

> if you find missing fields or other bugs, I'm happy to consider PRs to add them

I should start by updating the create Article model, just to be comfortable. Then I can go from there and find more inconsistencies and/or add new endpoints from the V1 of the API [even if it is stalled] to make the project updated.
